<?php
return [
  0 =>
    [
      'name'   => 'CRM_BlendleImport_Form_Report_BlendleRevenueReport',
      'entity' => 'ReportTemplate',
      'params' =>
        [
          'version'     => 3,
          'label'       => 'Blendle Revenue Report',
          'description' => 'Displays contributions and activities generated by the Blendle Data Import extension.',
          'class_name'  => 'CRM_BlendleImport_Form_Report_BlendleRevenueReport',
          'report_url'  => 'blendlerevenuereport',
          'component'   => 'CiviContribute',
        ],
    ],
];
